### ISSUE TITLE
Integrated Assay

### ISSUE THREAD

**Issue by angelussong** [jo-m-lab/ARBOL#1]
Hi, 

Thanks for publishing this very useful package! I am wondering which assay this package is compatible with. 

For example, if I have a Seurat object that was the integration of multiple 10x lanes. Could I use ARBOL to get the detailed structure trees? And if I could use ARBOL, should I switch the defaultassay from integrated to RNA before using ARBOL? 

Thank you!

**Comment by kylekimler** [comment]
Hi! 

I'm glad the package is helpful. With default parameters, ARBOL() iterative tiered clustering function should be used on a raw RNA counts assay. This is because the default "Preprocess_fun" uses SCTransform() normalization. If you want to normalize differently, or input your own pre-normalized or integrated data to ARBOL(), there is a Preprocess_fun option that does not normalize, "PreProcess_no_normalization" which you can input as the PreProcess_fun parameter. 

There are currently 4 options available for PreProcess_fun, which should be input without quotes, for example

`endclustDF <- ARBOL(srobj = srobj, tierAllowedRecomb=3, harmony_var = 'array',
							PreProcess_fun = PreProcess_sctransform_harmony,
                           saveSROBJdir = './arbol_srobjs',
                           figdir = './arbol_figs',
                           SaveEndNamesDir = './arbol_endclusts')`

The options for PreProcess_fun are as follows:
1. PreProcess
   Log1p normalization is performed
2. PreProcess_no_normalization
   no normalization is performed
3. PreProcess_sctransform (default)
   SCtransform normalization is performed
4. PreProcess_sctransform_harmony
   SCtransform normalization is performed AND harmony is used in place of PCA. If this option is chosen, you can specify an 
   integration variable for harmony using the ARBOL parameter `harmony_var` which reads in a string, the name of the batch 
   variable column found in your seurat object metadata.

Counts used by ARBOL currently must be placed in the "RNA" assay. ARBOL will always use the "RNA" assay until it performs SCTransform itself - then it switches to using the "SCT" assay. I suggest you place raw counts in the "RNA" assay and use the PreProcess_sctransform_harmony PreProcess_fun option with harmony_var set to your batch variable.

Thanks for trying the package!

**Comment by angelussong** [comment]
Thank you so much for your answer!! 

However, I ran into another issue when running the codes according to the ARBOL tutorial. 
After constructing the ARBOL tree, I would need to convert the tree to a phylo object and add the tip.label. 

`ARBOLphylo$tip.label <- ARBOLtree$Get('tierNident')[!is.na(ARBOLtree$Get('tierNident'))]`

For the dataset I was testing with, the length of tierNident was 168. But when I tried to run the plotdendrogram(), it always gave me a length not match error. The tree object ARBOLtree seems to be working fine with the output like this:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/40570906/206261861-49fe81e5-d8b4-4085-a03f-7eddf7e67e1d.png">

When I tried to debug it by running the lines in the plotdendrogram() one by one, the first line seems to be problematic. 
`dd.row <- as.dendrogram(phyloObj)`
The dd.row has only six rows, which is not the case. But I don't really know why that is or what might cause that. I am wondering if you have encountered similar issues before. Could you please help me with this?

**Comment by kylekimler** [comment]
Hi again! Sorry for the wait - because of all these inconsistencies with plotting using dendrogram objects, I've been planning a total revamp of plotting methods that uses tidygraph + ggraph which use ggplot grammar for tree and network plotting. I'll be releasing it today, I hope, alongside a new tutorial! I suggest trying out the new functions in the new tutorial when I release it.

**Comment by kylekimler** [comment]
Hi, were you able to try the new plotting tutorial? Does it work better than the old dendextend/phyloseq methods?

**Comment by kylekimler** [comment]
Closing this issue now - please open a new issue if you have questions about the new visualization methods. Thank you!
